package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblAdmin generated by hbm2java
 */
public class TblAdmin implements java.io.Serializable {

	private Integer id;
	private String fullName;
	private String username;
	private String password;
	private String email;
	private Date lastLoginTimestamp;
	private Set tblCmses = new HashSet(0);
	private Set tblJobPositions = new HashSet(0);

	public TblAdmin() {
	}

	public TblAdmin(String fullName, String username, String password, String email) {
		this.fullName = fullName;
		this.username = username;
		this.password = password;
		this.email = email;
	}

	public TblAdmin(String fullName, String username, String password, String email, Date lastLoginTimestamp,
			Set tblCmses, Set tblJobPositions) {
		this.fullName = fullName;
		this.username = username;
		this.password = password;
		this.email = email;
		this.lastLoginTimestamp = lastLoginTimestamp;
		this.tblCmses = tblCmses;
		this.tblJobPositions = tblJobPositions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getLastLoginTimestamp() {
		return this.lastLoginTimestamp;
	}

	public void setLastLoginTimestamp(Date lastLoginTimestamp) {
		this.lastLoginTimestamp = lastLoginTimestamp;
	}

	public Set getTblCmses() {
		return this.tblCmses;
	}

	public void setTblCmses(Set tblCmses) {
		this.tblCmses = tblCmses;
	}

	public Set getTblJobPositions() {
		return this.tblJobPositions;
	}

	public void setTblJobPositions(Set tblJobPositions) {
		this.tblJobPositions = tblJobPositions;
	}

}
