package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TblCountry generated by hbm2java
 */
public class TblCountry implements java.io.Serializable {

	private Integer id;
	private String title;
	private String nationality;
	private Set tblEmployees = new HashSet(0);
	private Set tblEntityAbstracts = new HashSet(0);

	public TblCountry() {
	}

	public TblCountry(String title, String nationality) {
		this.title = title;
		this.nationality = nationality;
	}

	public TblCountry(String title, String nationality, Set tblEmployees, Set tblEntityAbstracts) {
		this.title = title;
		this.nationality = nationality;
		this.tblEmployees = tblEmployees;
		this.tblEntityAbstracts = tblEntityAbstracts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public Set getTblEmployees() {
		return this.tblEmployees;
	}

	public void setTblEmployees(Set tblEmployees) {
		this.tblEmployees = tblEmployees;
	}

	public Set getTblEntityAbstracts() {
		return this.tblEntityAbstracts;
	}

	public void setTblEntityAbstracts(Set tblEntityAbstracts) {
		this.tblEntityAbstracts = tblEntityAbstracts;
	}

}
