package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TblCms generated by hbm2java
 */
public class TblCms implements java.io.Serializable {

	private Integer id;
	private TblAdmin tblAdmin;
	private String title;
	private String content;
	private Date lastModifiedOn;

	public TblCms() {
	}

	public TblCms(TblAdmin tblAdmin, String title, String content, Date lastModifiedOn) {
		this.tblAdmin = tblAdmin;
		this.title = title;
		this.content = content;
		this.lastModifiedOn = lastModifiedOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblAdmin getTblAdmin() {
		return this.tblAdmin;
	}

	public void setTblAdmin(TblAdmin tblAdmin) {
		this.tblAdmin = tblAdmin;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

}
