package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblEntityAbstract generated by hbm2java
 */
public class TblEntityAbstract implements java.io.Serializable {

	private Integer id;
	private TblCountry tblCountry;
	private String address1;
	private String address2;
	private String suburb;
	private String state;
	private String postcode;
	private Byte status;
	private Date createdDate;
	private String entityCode;
	private String username;
	private String password;
	private Set tblEntityAttachments = new HashSet(0);
	private Set tblEmployees = new HashSet(0);
	private Set tblEmployers = new HashSet(0);

	public TblEntityAbstract() {
	}

	public TblEntityAbstract(TblCountry tblCountry, String address1, String address2, String suburb, String state,
			String postcode, Byte status, Date createdDate, String entityCode, String username, String password,
			Set tblEntityAttachments, Set tblEmployees, Set tblEmployers) {
		this.tblCountry = tblCountry;
		this.address1 = address1;
		this.address2 = address2;
		this.suburb = suburb;
		this.state = state;
		this.postcode = postcode;
		this.status = status;
		this.createdDate = createdDate;
		this.entityCode = entityCode;
		this.username = username;
		this.password = password;
		this.tblEntityAttachments = tblEntityAttachments;
		this.tblEmployees = tblEmployees;
		this.tblEmployers = tblEmployers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblCountry getTblCountry() {
		return this.tblCountry;
	}

	public void setTblCountry(TblCountry tblCountry) {
		this.tblCountry = tblCountry;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getSuburb() {
		return this.suburb;
	}

	public void setSuburb(String suburb) {
		this.suburb = suburb;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getEntityCode() {
		return this.entityCode;
	}

	public void setEntityCode(String entityCode) {
		this.entityCode = entityCode;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getTblEntityAttachments() {
		return this.tblEntityAttachments;
	}

	public void setTblEntityAttachments(Set tblEntityAttachments) {
		this.tblEntityAttachments = tblEntityAttachments;
	}

	public Set getTblEmployees() {
		return this.tblEmployees;
	}

	public void setTblEmployees(Set tblEmployees) {
		this.tblEmployees = tblEmployees;
	}

	public Set getTblEmployers() {
		return this.tblEmployers;
	}

	public void setTblEmployers(Set tblEmployers) {
		this.tblEmployers = tblEmployers;
	}

}
