package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TblEmployer generated by hbm2java
 */
public class TblEmployer implements java.io.Serializable {

	private Integer id;
	private TblEntityAbstract tblEntityAbstract;
	private String companyName;
	private String contactPerson;
	private String email;
	private String companyNumber;
	private String contactPersonPosition;
	private String mobile;
	private String workPhone;
	private String geocodedLatitude;
	private String geocodedLongitude;
	private Set tblJobs = new HashSet(0);

	public TblEmployer() {
	}

	public TblEmployer(TblEntityAbstract tblEntityAbstract, String companyName, String contactPerson, String email,
			String companyNumber) {
		this.tblEntityAbstract = tblEntityAbstract;
		this.companyName = companyName;
		this.contactPerson = contactPerson;
		this.email = email;
		this.companyNumber = companyNumber;
	}

	public TblEmployer(TblEntityAbstract tblEntityAbstract, String companyName, String contactPerson, String email,
			String companyNumber, String contactPersonPosition, String mobile, String workPhone,
			String geocodedLatitude, String geocodedLongitude, Set tblJobs) {
		this.tblEntityAbstract = tblEntityAbstract;
		this.companyName = companyName;
		this.contactPerson = contactPerson;
		this.email = email;
		this.companyNumber = companyNumber;
		this.contactPersonPosition = contactPersonPosition;
		this.mobile = mobile;
		this.workPhone = workPhone;
		this.geocodedLatitude = geocodedLatitude;
		this.geocodedLongitude = geocodedLongitude;
		this.tblJobs = tblJobs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblEntityAbstract getTblEntityAbstract() {
		return this.tblEntityAbstract;
	}

	public void setTblEntityAbstract(TblEntityAbstract tblEntityAbstract) {
		this.tblEntityAbstract = tblEntityAbstract;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCompanyNumber() {
		return this.companyNumber;
	}

	public void setCompanyNumber(String companyNumber) {
		this.companyNumber = companyNumber;
	}

	public String getContactPersonPosition() {
		return this.contactPersonPosition;
	}

	public void setContactPersonPosition(String contactPersonPosition) {
		this.contactPersonPosition = contactPersonPosition;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	public String getGeocodedLatitude() {
		return this.geocodedLatitude;
	}

	public void setGeocodedLatitude(String geocodedLatitude) {
		this.geocodedLatitude = geocodedLatitude;
	}

	public String getGeocodedLongitude() {
		return this.geocodedLongitude;
	}

	public void setGeocodedLongitude(String geocodedLongitude) {
		this.geocodedLongitude = geocodedLongitude;
	}

	public Set getTblJobs() {
		return this.tblJobs;
	}

	public void setTblJobs(Set tblJobs) {
		this.tblJobs = tblJobs;
	}

}
