package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblEmployee generated by hbm2java
 */
public class TblEmployee implements java.io.Serializable {

	private Integer id;
	private TblCountry tblCountry;
	private TblEntityAbstract tblEntityAbstract;
	private String firstName;
	private String lastName;
	private String email;
	private String mobile;
	private String socialMediaParams;
	private String passwordKey;
	private String photoFile;
	private Byte gender;
	private Integer maxHoursPerFortnight;
	private Date dob;
	private Date startDate;
	private String homePhone;
	private String workPhone;
	private Set tblJobStatuses = new HashSet(0);

	public TblEmployee() {
	}

	public TblEmployee(TblEntityAbstract tblEntityAbstract, String firstName, String lastName, String email,
			String mobile) {
		this.tblEntityAbstract = tblEntityAbstract;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.mobile = mobile;
	}

	public TblEmployee(TblCountry tblCountry, TblEntityAbstract tblEntityAbstract, String firstName, String lastName,
			String email, String mobile, String socialMediaParams, String passwordKey, String photoFile, Byte gender,
			Integer maxHoursPerFortnight, Date dob, Date startDate, String homePhone, String workPhone,
			Set tblJobStatuses) {
		this.tblCountry = tblCountry;
		this.tblEntityAbstract = tblEntityAbstract;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.mobile = mobile;
		this.socialMediaParams = socialMediaParams;
		this.passwordKey = passwordKey;
		this.photoFile = photoFile;
		this.gender = gender;
		this.maxHoursPerFortnight = maxHoursPerFortnight;
		this.dob = dob;
		this.startDate = startDate;
		this.homePhone = homePhone;
		this.workPhone = workPhone;
		this.tblJobStatuses = tblJobStatuses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblCountry getTblCountry() {
		return this.tblCountry;
	}

	public void setTblCountry(TblCountry tblCountry) {
		this.tblCountry = tblCountry;
	}

	public TblEntityAbstract getTblEntityAbstract() {
		return this.tblEntityAbstract;
	}

	public void setTblEntityAbstract(TblEntityAbstract tblEntityAbstract) {
		this.tblEntityAbstract = tblEntityAbstract;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getSocialMediaParams() {
		return this.socialMediaParams;
	}

	public void setSocialMediaParams(String socialMediaParams) {
		this.socialMediaParams = socialMediaParams;
	}

	public String getPasswordKey() {
		return this.passwordKey;
	}

	public void setPasswordKey(String passwordKey) {
		this.passwordKey = passwordKey;
	}

	public String getPhotoFile() {
		return this.photoFile;
	}

	public void setPhotoFile(String photoFile) {
		this.photoFile = photoFile;
	}

	public Byte getGender() {
		return this.gender;
	}

	public void setGender(Byte gender) {
		this.gender = gender;
	}

	public Integer getMaxHoursPerFortnight() {
		return this.maxHoursPerFortnight;
	}

	public void setMaxHoursPerFortnight(Integer maxHoursPerFortnight) {
		this.maxHoursPerFortnight = maxHoursPerFortnight;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	public String getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	public Set getTblJobStatuses() {
		return this.tblJobStatuses;
	}

	public void setTblJobStatuses(Set tblJobStatuses) {
		this.tblJobStatuses = tblJobStatuses;
	}

}
