package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TblEntityAttachment generated by hbm2java
 */
public class TblEntityAttachment implements java.io.Serializable {

	private Integer id;
	private TblAttachment tblAttachment;
	private TblEntityAbstract tblEntityAbstract;
	private Date expiryDate;
	private String references;
	private String comments;
	private Date lastModifiedDate;
	private int lastModifiedBy;
	private String attachmentFile;
	private byte entityType;
	private Byte emailStatus;

	public TblEntityAttachment() {
	}

	public TblEntityAttachment(TblAttachment tblAttachment, TblEntityAbstract tblEntityAbstract, Date expiryDate,
			String references, String comments, Date lastModifiedDate, int lastModifiedBy, byte entityType) {
		this.tblAttachment = tblAttachment;
		this.tblEntityAbstract = tblEntityAbstract;
		this.expiryDate = expiryDate;
		this.references = references;
		this.comments = comments;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedBy = lastModifiedBy;
		this.entityType = entityType;
	}

	public TblEntityAttachment(TblAttachment tblAttachment, TblEntityAbstract tblEntityAbstract, Date expiryDate,
			String references, String comments, Date lastModifiedDate, int lastModifiedBy, String attachmentFile,
			byte entityType, Byte emailStatus) {
		this.tblAttachment = tblAttachment;
		this.tblEntityAbstract = tblEntityAbstract;
		this.expiryDate = expiryDate;
		this.references = references;
		this.comments = comments;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedBy = lastModifiedBy;
		this.attachmentFile = attachmentFile;
		this.entityType = entityType;
		this.emailStatus = emailStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblAttachment getTblAttachment() {
		return this.tblAttachment;
	}

	public void setTblAttachment(TblAttachment tblAttachment) {
		this.tblAttachment = tblAttachment;
	}

	public TblEntityAbstract getTblEntityAbstract() {
		return this.tblEntityAbstract;
	}

	public void setTblEntityAbstract(TblEntityAbstract tblEntityAbstract) {
		this.tblEntityAbstract = tblEntityAbstract;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getReferences() {
		return this.references;
	}

	public void setReferences(String references) {
		this.references = references;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public int getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(int lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public String getAttachmentFile() {
		return this.attachmentFile;
	}

	public void setAttachmentFile(String attachmentFile) {
		this.attachmentFile = attachmentFile;
	}

	public byte getEntityType() {
		return this.entityType;
	}

	public void setEntityType(byte entityType) {
		this.entityType = entityType;
	}

	public Byte getEmailStatus() {
		return this.emailStatus;
	}

	public void setEmailStatus(Byte emailStatus) {
		this.emailStatus = emailStatus;
	}

}
