package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

/**
 * TblJobStatus generated by hbm2java
 */
public class TblJobStatus implements java.io.Serializable {

	private Integer id;
	private TblEmployee tblEmployee;
	private TblJob tblJob;
	private byte jobStatus;

	public TblJobStatus() {
	}

	public TblJobStatus(TblEmployee tblEmployee, TblJob tblJob, byte jobStatus) {
		this.tblEmployee = tblEmployee;
		this.tblJob = tblJob;
		this.jobStatus = jobStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblEmployee getTblEmployee() {
		return this.tblEmployee;
	}

	public void setTblEmployee(TblEmployee tblEmployee) {
		this.tblEmployee = tblEmployee;
	}

	public TblJob getTblJob() {
		return this.tblJob;
	}

	public void setTblJob(TblJob tblJob) {
		this.tblJob = tblJob;
	}

	public byte getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(byte jobStatus) {
		this.jobStatus = jobStatus;
	}

}
