package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

/**
 * TblMessage generated by hbm2java
 */
public class TblMessage implements java.io.Serializable {

	private Integer id;
	private String title;
	private String subject;
	private String content;
	private byte messageType;

	public TblMessage() {
	}

	public TblMessage(String title, String subject, String content, byte messageType) {
		this.title = title;
		this.subject = subject;
		this.content = content;
		this.messageType = messageType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public byte getMessageType() {
		return this.messageType;
	}

	public void setMessageType(byte messageType) {
		this.messageType = messageType;
	}

}
