package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

/**
 * TblPasswordResetRequest generated by hbm2java
 */
public class TblPasswordResetRequest implements java.io.Serializable {

	private Integer id;
	private String idKey;
	private String userType;
	private int userId;

	public TblPasswordResetRequest() {
	}

	public TblPasswordResetRequest(String idKey, String userType, int userId) {
		this.idKey = idKey;
		this.userType = userType;
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIdKey() {
		return this.idKey;
	}

	public void setIdKey(String idKey) {
		this.idKey = idKey;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
