package com.nurseaid.model;
// Generated Sep 26, 2016 12:31:45 PM by Hibernate Tools 4.3.1.Final

/**
 * TblSettings generated by hbm2java
 */
public class TblSettings implements java.io.Serializable {

	private Integer id;
	private String title;
	private String value;
	private String type;

	public TblSettings() {
	}

	public TblSettings(String title, String value, String type) {
		this.title = title;
		this.value = value;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
